### ISSUE TITLE
Kryo Serialization Not Working.

### ISSUE THREAD

**Issue by iamanandkris** [iamanandkris/crawler#2]
Hello @romix could you please have a look at the below issue I am facing with Kryo serialization?

I want to serialize a Case Class (crawlerinformation.CreateEvent). My config (https://github.com/iamanandkris/crawler/blob/master/conf/frontend.conf) for AKKA is like this:

```
akka {
  loglevel = DEBUG
  stdout-loglevel = DEBUG
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  extensions = ["com.romix.akka.serialization.kryo.KryoSerializationExtension$"]

  actor {
    provider = "akka.remote.RemoteActorRefProvider"
    kryo {
      type = "graph"
      idstrategy = "incremental"
      buffer-size = 4096
      max-buffer-size = -1
      use-manifest = false
      implicit-registration-logging = true
      kryo-trace = true

      mappings {
        "crawlerinformation.CreateEvent" = 32
      }
    }

    serialize-messages = on
    serializers {
      #java = "akka.serialization.JavaSerializer"
      kryo = "com.romix.akka.serialization.kryo.KryoSerializer"
    }
    serialization-bindings {
      "crawlerinformation.CreateEvent" = kryo
    }
  }
```

I get an error when the server is invoked (A Get call to the controller which then sends the CreateEvent message to another distributed actor):

```
[error] c.r.a.s.k.KryoSerializer(akka://frontend) - Class could not be loaded and/or registered: crawlerinformation.CreateEvent
[error] c.r.a.s.k.KryoSerializer(akka://frontend) - exception caught during akka-kryo-serialization startup: java.lang.ClassNotFoundException: crawlerinformation.CreateEvent
[error] a.a.LocalActorRefProvider$SystemGuardian - swallowing exception during message send
```

Full Error Log Below:

```

--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/AnandKrishnan/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/AnandKrishnan/.ivy2/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/activator-dist-1.3.5/repository/org.slf4j/slf4j-simple/1.7.7/jars/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
[info] play - Application started (Dev)
[DEBUG] [07/19/2016 10:34:46.620] [New I/O worker #1] [EventStream] StandardOutLogger started
[DEBUG] [07/19/2016 10:34:46.831] [New I/O worker #1] [EventStream(akka://frontend)] logger log1-Slf4jLogger started
[DEBUG] [07/19/2016 10:34:46.831] [New I/O worker #1] [EventStream(akka://frontend)] Default Loggers started
00:00 TRACE: [kryo] Registration required: false
[error] c.r.a.s.k.KryoSerializer(akka://frontend) - Class could not be loaded and/or registered: crawlerinformation.CreateEvent
[error] c.r.a.s.k.KryoSerializer(akka://frontend) - exception caught during akka-kryo-serialization startup: java.lang.ClassNotFoundException: crawlerinformation.CreateEvent
[error] a.a.LocalActorRefProvider$SystemGuardian - swallowing exception during message send
java.lang.ClassNotFoundException: crawlerinformation.CreateEvent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_45]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45]
        at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_45]
[error] application -

! Internal server error, for (GET) [/crawl] ->

java.lang.ExceptionInInitializerError: null
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:87) ~[na:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:87) ~[na:na]
        at play.core.Router$HandlerInvokerFactory$$anon$13$$anon$14.call(Router.scala:217) ~[play_2.11-2.3.2.jar:2.3.2]
        at play.core.Router$Routes$TaggingInvoker.call(Router.scala:464) ~[play_2.11-2.3.2.jar:2.3.2]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2.apply(routes_routing.scala:87) ~[na:na]
Caused by: java.lang.ClassNotFoundException: crawlerinformation.CreateEvent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_45]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45]
        at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_45]
[error] application - Error while rendering default error page
scala.MatchError: java.lang.ExceptionInInitializerError (of class java.lang.ExceptionInInitializerError)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:148) ~[play_2.11-2.3.2.jar:2.3.2]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:206) [play_2.11-2.3.2.jar:2.3.2]
        at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:76) [play_2.11-2.3.2.jar:2.3.2]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:86) [play_2.11-2.3.2.jar:2.3.2]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:84) [play_2.11-2.3.2.jar:2.3.2]
```

Thank you

**Comment by iamanandkris** [comment]
I am using 
Java - 1.8.0_45
Scala - 2.11.5
AKKA - 2.4.7
Kryo - 0.4.1
